on: [ push ]

jobs:
  test_setup_python:
    strategy:
      matrix:
        # This tests the amazon linux versions receiving standard support
        # Refer - https://endoflife.date/amazon-linux
        amazon-linux-version: [ 2, 2023 ]
        # This tests the lowest supported python version and the latest stable python version
        # Refer - https://devguide.python.org/versions/#status-of-python-versions
        python-version: [ 3.8, 3.12 ]
    runs-on: ubuntu-latest
    container: amazonlinux:${{ matrix.amazon-linux-version }}
    steps:
      - name: Setup runner
        run: |
          yum install -y git tar gzip
      - uses: actions/checkout@v3
      - name: Install python
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test installation
        run: |
          python --version 2>&1 | grep -F "${{ matrix.python-version }}"
