on: [push]

jobs:
  test_setup_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: ./
        with:
          python-version: 3.8
      - name: Test installation
        run: |
          python --version
